"""WalletQueryOrm.balance_trx migration with int to Decimal

Revision ID: 522714626657
Revises: cb80ecb066e2
Create Date: 2025-07-27 16:10:39.243798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522714626657'
down_revision: Union[str, Sequence[str], None] = 'cb80ecb066e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_queries', 'balance_trx',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_queries', 'balance_trx',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
