"""torn init

Revision ID: cb80ecb066e2
Revises: 
Create Date: 2025-07-26 22:49:51.421765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb80ecb066e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_queries',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('bandwidth', sa.BigInteger(), nullable=False),
    sa.Column('energy', sa.BigInteger(), nullable=False),
    sa.Column('balance_trx', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_wallet_queries_address'), 'wallet_queries', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_queries_address'), table_name='wallet_queries')
    op.drop_table('wallet_queries')
    # ### end Alembic commands ###
